
matrix:
  include:
    - os: osx
      osx_image: xcode9

before_install:
  - git clone https://github.com/sandmman/Package-Builder.git

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -version ; fi
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
