
matrix:
  include:
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode9.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -version ; fi
script:
