
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      sudo: required

before_install:
  - git clone https://github.com/sandmman/Package-Builder.git

script:
  - cd Package-Builder
  - git checkout jazzy_travis
  - cd ..
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -version ; fi
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
