
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
  - git clone https://github.com/ShihabMehboob/Package-Builder.git

script:
  - git checkout jazzy_travis
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -version ; fi
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
